### ISSUE TITLE
Can't build examples

### ISSUE THREAD

**Issue by agnieszka-dev** [plule/dfhack-remote#11]
Hi there, I'm a beginner at rust and trying to build example code provided in dfhack-remote/examples. 

Trying to build [run.rs](https://github.com/plule/dfhack-remote/blob/main/examples/run.rs) throws following errors:

![Image](https://github.com/user-attachments/assets/2d08d39a-132a-48fe-a2b1-959436ce5f87)

And trying to build [pause_unpause.rs](https://github.com/plule/dfhack-remote/blob/main/examples/pause_unpause.rs) throws following error:

![Image](https://github.com/user-attachments/assets/2fa70e79-4691-486e-87d2-c0547bde56d5)

I'll be grateful for any help!

**Comment by agnieszka-dev** [comment]
Ok, I figured it out - I changed this:

```toml
[dependencies]
dfhack-remote = "0.9.0"
```

to this:

```toml
[dependencies]
dfhack-remote = { git = "https://github.com/plule/dfhack-remote.git" }
```

in my Cargo.toml, and all works now. Cheers!
